In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# NumPy Pair Problem

For today's pair, we will use NumPy to complete the following tasks consecutively.

In [ ]:
import numpy as np

# Set random seed so that results are reproducible
np.random.seed(0)

### 1. Generate three separate 1-dimensional arrays of 10,000 elements each.
* Array 1 should contain numbers randomly drawn from the uniform distribution between 1 and 100
* Array 2 should contain numbers randomly drawn from the normal distribution, with a mean of 0 and a standard deviation of 1
* Array 3 should contain numbers randomly drawn from the binomial distribution, where n=10 and p=0.5

In [ ]:
array1 = np.random.uniform(1, 100, 10000)
array1

array([55.33253689, 71.80374727, 60.67357423, ..., 76.08452255,
        3.35495532, 81.54393292])

In [ ]:
array2 = np.random.normal(0, 1, 10000)
array2

array([-0.72582032,  0.56347552, -0.43563209, ..., -0.48621622,
       -2.04550028,  1.03931951])

In [ ]:
array3 = np.random.binomial(10, 0.5, 10000)
array3

array([4, 5, 5, ..., 5, 4, 4])

### 2. For each array, randomly sample 1,000 rows without replacement. (hint: `np.random.choice()`)


In [ ]:
array4 = np.random.choice(array1, size=1000)
array4

array([24.915263  , 95.70058403, 64.56003116, 32.33771343, 39.991819  ,
       31.71827429, 68.3088615 , 87.95059037, 51.85523244, 39.56530223,
       78.99709505, 89.75461494, 57.65453052, 27.85537426, 11.10243626,
       85.84271041, 30.39947259, 29.20366653, 76.31847024, 45.31639392,
       41.68986959, 63.1428607 , 42.61502713, 25.92584158, 73.6734921 ,
       73.50415165, 77.84239391, 77.61243355, 84.81589155, 52.22053161,
       58.35460659, 68.16347255, 12.47229411, 25.9039876 , 28.20959503,
       95.15587308, 77.39954838, 77.20911305, 49.35530297, 22.1149184 ,
       29.87494721, 78.10669663, 96.43302436, 37.98024291, 86.14298364,
       55.14160527, 20.89954269, 82.02379406, 51.24809339,  1.72082038,
       12.03199525, 80.65917455, 69.92570082, 46.81336172, 33.30069363,
       36.70286437, 59.03971597,  4.03544378, 10.59884953, 26.02510756,
       91.7460561 ,  6.480275  , 10.47446789, 74.47807291, 30.86845589,
       93.12411084, 50.23894857, 47.29030304,  1.49867725, 23.01

In [ ]:
array5 = np.random.choice(array2, size=1000)
array5

array([-0.55107553,  1.07079756,  2.27707735,  0.34192388,  1.26956702,
       -0.91458701, -0.61076885, -0.11599909,  0.64535844, -1.026073  ,
        0.21925025, -0.19791961, -0.54963579,  0.18912665,  0.40430755,
        0.19018834, -0.23148788,  0.68636976, -0.9822015 , -1.78974961,
        0.67358988, -0.20616888, -1.34631888, -1.3544978 , -0.17014623,
        0.58450237, -1.3439731 ,  0.27830267, -1.83846145,  2.44009195,
       -0.03932824,  0.14445854,  0.15440531,  1.49806999, -2.50680398,
        0.81218629,  0.75488063, -0.75120398, -0.6958142 , -0.90765619,
       -0.30717456, -0.59842614, -0.9054312 ,  0.73731091, -0.60456653,
        0.434387  , -0.30986864, -0.97496027,  1.02116608,  0.62942136,
       -0.14744327, -0.53790629,  0.01770283,  1.16088899,  0.31847233,
        0.70312324, -0.20134816,  0.44756546, -1.83584958,  0.356926  ,
        0.05424776, -0.72116475, -2.39544732, -0.12988079,  0.72062307,
       -0.78834115, -0.22426994, -0.93305007,  0.06488494,  1.90

In [ ]:
arrary6 = np.random.choice(array3, size=1000)
arrary6

array([ 3,  3,  5,  4,  5,  2,  3,  7,  3,  4,  4,  3,  4,  2,  5,  2,  6,
        6,  3,  5,  4,  6,  6,  6,  4,  6,  4,  5,  4,  4,  5,  6,  5,  5,
        4,  4,  6,  6,  4,  4,  8,  6,  2,  5,  5,  4,  2,  7,  4,  3,  7,
        7,  5,  6,  7,  5,  3,  3,  4,  7,  5,  6,  1,  7,  5,  5,  6,  6,
        6,  6,  4,  6,  8,  6,  3,  4,  2,  7,  5,  4,  3,  5,  5,  7,  3,
        5,  3,  7,  6,  6,  2,  4,  5,  6,  8,  4,  4,  7,  5,  3,  5,  8,
        6,  6,  8,  2,  3,  5,  7,  3,  5,  7,  4,  4,  3,  3,  5,  7,  5,
        7,  2,  5,  8,  7,  7,  4,  8,  5,  6,  6,  4,  2,  5,  6,  7,  6,
        2,  7,  4,  4,  5,  5,  6,  6,  5,  6,  6,  5,  4,  6,  4,  3,  7,
        5,  5,  7,  3,  5,  6, 10,  4,  5,  6,  4,  8,  3,  7,  6,  7,  7,
        3,  5,  2,  4,  4,  4,  4,  7,  2,  5,  2,  5,  6,  5,  5,  6,  3,
        5,  6,  7,  6,  3,  3,  5,  6,  4,  6,  6,  4,  4,  7,  5,  9,  8,
        2,  3,  5,  5,  7,  4,  5,  7,  4,  5,  3,  4,  2,  7,  9,  3,  4,
        5,  5,  5,  5,  2

### 3. For each of the three samples:  
- Calculate the mean, median, and standard deviation
- Find the index and the value of the largest element (hint: `np.argmax()`)  
- Find the value of the 75th percentile (hint: `np.percentile()`)  

In [ ]:
# mean
mean1= array4.mean()
mean1

# median
median1 = np.median(array4)
median1

# STD
std1 = np.std(array4)
std1

# max
max1 = np.max(array4)
max1

max_index = np.argmax(array4)
max_index

# 3rd quartile
q3_1 = np.percentile(array4, 75)
q3_1


50.82621553932708

50.80078079907237

28.344086106903127

99.91107588904035

673

77.19275200736246

In [ ]:
# mean
mean2= array5.mean()
mean2

# median
median2 = np.median(array5)
median2

# STD
std2 = np.std(array5)
std2

# max
max2 = np.max(array5)
max2

max_index = np.argmax(array5)
max_index

# 3rd quartile
q3_2 = np.percentile(array5, 75)
q3_2

0.04316625036902359

0.08418759328592758

1.0048393833805247

3.220501789041126

417

0.7272935752617089

In [ ]:
# mean
mean3 = arrary6.mean()
mean3

# median
median3 = np.median(arrary6)
median3

# STD
std3 = np.std(arrary6)
std3

# max
max3 = np.max(arrary6)
max3

max_index = np.argmax(arrary6)
max_index

# 3rd quartile
q3_3 = np.percentile(arrary6, 75)
q3_3


5.031

5.0

1.5297186015735051

10

159

6.0

### 4. Sort each of the three samples in increasing order, then combine them together to create a 1,000 by 3 array. (hint: `np.sort()` and `np.stack()`). Now, check the shape of the array.

In [ ]:
array4_sorted = np.sort(array4)

array5_sorted = np.sort(array5)

array6_sorted = np.sort(arrary6)

In [ ]:
all_samples = np.stack((array4_sorted, array5_sorted, array6_sorted), axis=1)
all_samples

array([[ 1.01488773, -3.59716335,  1.        ],
       [ 1.06575764, -2.99396   ,  1.        ],
       [ 1.12840798, -2.95864333,  1.        ],
       ...,
       [99.61394359,  2.71614524,  9.        ],
       [99.66627505,  2.76054867, 10.        ],
       [99.91107589,  3.22050179, 10.        ]])

### 5. Replace all negative values with 0.

Replace all values that exceed 10 with 10.

In [ ]:
condition = all_samples < 0
condition

array([[False,  True, False],
       [False,  True, False],
       [False,  True, False],
       ...,
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
all_samples[condition]

array([-3.59716335, -2.99396   , -2.95864333, -2.68544711, -2.67841292,
       -2.55369516, -2.523029  , -2.52204841, -2.50680398, -2.4987997 ,
       -2.39544732, -2.39544732, -2.39384941, -2.38112855, -2.31983213,
       -2.31983213, -2.31270349, -2.17027215, -2.12603428, -2.11944084,
       -2.09998339, -2.07706298, -2.05519135, -2.0452586 , -2.03786682,
       -1.99703344, -1.97396705, -1.91160696, -1.90986072, -1.90175861,
       -1.89374671, -1.85835446, -1.85358843, -1.83846145, -1.83584958,
       -1.80015327, -1.79884394, -1.78974961, -1.77322367, -1.76648611,
       -1.76113205, -1.74698457, -1.712146  , -1.69944214, -1.67524907,
       -1.66638251, -1.64241705, -1.64053316, -1.63887149, -1.63495806,
       -1.63451753, -1.60559466, -1.60004008, -1.59373823, -1.58019101,
       -1.56554179, -1.55715934, -1.55632374, -1.54585996, -1.53552666,
       -1.53392185, -1.51803382, -1.51641374, -1.50533659, -1.50452576,
       -1.49848251, -1.4928582 , -1.4928582 , -1.48420989, -1.47

In [ ]:
all_samples_modified = np.clip(all_samples, 0, 10)
all_samples_modified

array([[ 1.01488773,  0.        ,  1.        ],
       [ 1.06575764,  0.        ,  1.        ],
       [ 1.12840798,  0.        ,  1.        ],
       ...,
       [10.        ,  2.71614524,  9.        ],
       [10.        ,  2.76054867, 10.        ],
       [10.        ,  3.22050179, 10.        ]])

### 6. Subtract 5 from all values that exceed 5. (hint: `np.where()`)

In [ ]:
all_samples_modified = np.where(all_samples_modified > 5, all_samples_modified - 5, all_samples_modified)
all_samples_modified

array([[1.01488773, 0.        , 1.        ],
       [1.06575764, 0.        , 1.        ],
       [1.12840798, 0.        , 1.        ],
       ...,
       [5.        , 2.71614524, 4.        ],
       [5.        , 2.76054867, 5.        ],
       [5.        , 3.22050179, 5.        ]])

### 7. Produce a fourth column that is the sum of the first two columns.  (hint: `np.hstack()`). Now check the new shape of the array.

In [ ]:
sum_first_two_columns = all_samples_modified[:, 0:2].sum(axis=1)
sum_first_two_columns.shape
sum_first_two_columns = sum_first_two_columns.reshape(1000, 1)

(1000,)

In [ ]:
final_sample = np.hstack((all_samples_modified, sum_first_two_columns))
final_sample

array([[1.01488773, 0.        , 1.        , 1.01488773],
       [1.06575764, 0.        , 1.        , 1.06575764],
       [1.12840798, 0.        , 1.        , 1.12840798],
       ...,
       [5.        , 2.71614524, 4.        , 7.71614524],
       [5.        , 2.76054867, 5.        , 7.76054867],
       [5.        , 3.22050179, 5.        , 8.22050179]])

### 8. Use broadcasting to add 1 to each element of the first column, 2 to each element of the second column, 3 to each element of the third column, and 4 to each element of the fourth column.

In [ ]:
final_sample[:, 0] = final_sample[:, 0] + 1
final_sample[:, 1] = final_sample[:, 1] + 2
final_sample[:, 2] = final_sample[:, 2] + 3
final_sample[:, 3] = final_sample[:, 3] + 4

final_sample

array([[ 2.01488773,  2.        ,  4.        ,  5.01488773],
       [ 2.06575764,  2.        ,  4.        ,  5.06575764],
       [ 2.12840798,  2.        ,  4.        ,  5.12840798],
       ...,
       [ 6.        ,  4.71614524,  7.        , 11.71614524],
       [ 6.        ,  4.76054867,  8.        , 11.76054867],
       [ 6.        ,  5.22050179,  8.        , 12.22050179]])

### 9. Matrix multiply this 1000x4 array by a 4x1 array of ones. How many unique values are in the resulting product?  (hint: `np.unique()`)

In [ ]:
ones = np.ones((4, 1))

product = np.dot(final_sample, ones)
product

# product = final_sample @ ones

unique_values = np.unique(product)
unique_values.shape

array([[13.02977545],
       [13.13151528],
       [13.25681596],
       [13.25681596],
       [13.29086322],
       [13.40879784],
       [14.53972206],
       [14.96846053],
       [14.9973545 ],
       [15.08797393],
       [15.44164076],
       [15.55484041],
       [15.65085633],
       [15.71004516],
       [16.01580283],
       [16.05713153],
       [16.28674965],
       [16.38317213],
       [16.399641  ],
       [16.40988907],
       [16.77520224],
       [17.22803349],
       [17.34059133],
       [17.58307892],
       [17.80025327],
       [17.80679876],
       [17.88124215],
       [18.85740639],
       [18.87367655],
       [18.89831975],
       [19.12777876],
       [19.4867284 ],
       [19.51972825],
       [19.57639473],
       [19.79564614],
       [19.85381854],
       [19.85538631],
       [20.07088757],
       [20.07088757],
       [20.52319881],
       [20.54876911],
       [21.13469585],
       [21.34550231],
       [21.35166157],
       [12.04553991],
       [12

(587,)

# Thank You